import type {
  ActivityEvent,
  Alert,
  Client,
  ComplianceDocRecord,
  DocumentRecord,
  Submission,
} from "./types";

export interface DemoSeed {
  clients: Client[];
  documents: DocumentRecord[];
  compliance: ComplianceDocRecord[];
  submissions: Submission[];
  alerts: Alert[];
  activity: ActivityEvent[];
}

function isoDaysOffset(now: Date, offset: number) {
  return new Date(now.getTime() + offset * 24 * 60 * 60 * 1000).toISOString();
}

export function buildDemoSeed(now = new Date()): DemoSeed {
  const clients: Client[] = [
    {
      id: "cl_marie_laurent",
      createdAt: isoDaysOffset(now, -124),
      updatedAt: isoDaysOffset(now, -1),
      firstName: "Marie",
      lastName: "Laurent",
      email: "marie.laurent@demo.fr",
      phone: "06 58 14 29 33",
      dob: "1981-02-14",
      maritalStatus: "marie",
      taxResidence: "France",
      profession: "Dirigeante d'agence immobiliere",
      employer: "Laurent Prestige Conseil",
      address: {
        street: "14 avenue de Breteuil",
        postalCode: "75007",
        city: "Paris",
        country: "France",
      },
      financial: {
        annualIncome: 162000,
        netWorth: 1680000,
        realEstateValue: 930000,
        financialAssets: 462000,
        liabilities: 185000,
        monthlySavingsCapacity: 4200,
      },
      assets: [
        { id: "asset_ml_1", type: "immobilier", label: "Residence principale", value: 780000, ownership: 100 },
        { id: "asset_ml_2", type: "financier", label: "Contrats assurance vie", value: 315000, ownership: 100 },
        { id: "asset_ml_3", type: "financier", label: "PEA et compte-titres", value: 147000, ownership: 100 },
      ],
      riskProfile: "equilibre",
      kycStatus: "complet",
      nextReviewAt: isoDaysOffset(now, 22),
      tags: ["VIP", "Transmission", "Immobilier"],
      notes:
        "Preparation d'une strategie de transmission avec arbitrages progressifs vers une allocation plus diversifiee.",
    },
    {
      id: "cl_paul_bernard",
      createdAt: isoDaysOffset(now, -92),
      updatedAt: isoDaysOffset(now, -3),
      firstName: "Paul",
      lastName: "Bernard",
      email: "paul.bernard@demo.fr",
      phone: "06 71 52 80 11",
      dob: "1973-09-03",
      maritalStatus: "marie",
      taxResidence: "France",
      profession: "Directeur administratif et financier",
      employer: "Groupe Novence",
      address: {
        street: "8 rue du Mail",
        postalCode: "69002",
        city: "Lyon",
        country: "France",
      },
      financial: {
        annualIncome: 128000,
        netWorth: 1120000,
        realEstateValue: 510000,
        financialAssets: 385000,
        liabilities: 90000,
        monthlySavingsCapacity: 3100,
      },
      assets: [
        { id: "asset_pb_1", type: "immobilier", label: "Residence principale", value: 510000, ownership: 100 },
        { id: "asset_pb_2", type: "financier", label: "Contrat multisupport", value: 260000, ownership: 100 },
        { id: "asset_pb_3", type: "professionnel", label: "Parts societaires", value: 180000, ownership: 30 },
      ],
      riskProfile: "dynamique",
      kycStatus: "en_cours",
      nextReviewAt: isoDaysOffset(now, 11),
      tags: ["Retraite", "Assurance vie"],
      notes: "Projet de diversification de tresorerie privee et optimisation de preparation retraite.",
    },
    {
      id: "cl_sophie_mercier",
      createdAt: isoDaysOffset(now, -78),
      updatedAt: isoDaysOffset(now, -6),
      firstName: "Sophie",
      lastName: "Mercier",
      email: "sophie.mercier@demo.fr",
      phone: "07 83 49 72 15",
      dob: "1988-06-29",
      maritalStatus: "pacse",
      taxResidence: "France",
      profession: "Chirurgienne-dentiste",
      employer: "Cabinet Mercier",
      address: {
        street: "19 boulevard Michelet",
        postalCode: "13008",
        city: "Marseille",
        country: "France",
      },
      financial: {
        annualIncome: 184000,
        netWorth: 940000,
        realEstateValue: 320000,
        financialAssets: 438000,
        liabilities: 68000,
        monthlySavingsCapacity: 5600,
      },
      assets: [
        { id: "asset_sm_1", type: "financier", label: "Portefeuille titres", value: 230000, ownership: 100 },
        { id: "asset_sm_2", type: "financier", label: "Assurance vie luxembourgeoise", value: 208000, ownership: 100 },
        { id: "asset_sm_3", type: "immobilier", label: "Appartement locatif", value: 320000, ownership: 100 },
      ],
      riskProfile: "offensif",
      kycStatus: "en_attente",
      nextReviewAt: isoDaysOffset(now, 37),
      tags: ["Profession liberale", "Luxembourg"],
      notes: "Attente du justificatif de domicile et arbitrage final sur un contrat haut de gamme.",
    },
    {
      id: "cl_antoine_martin",
      createdAt: isoDaysOffset(now, -63),
      updatedAt: isoDaysOffset(now, -10),
      firstName: "Antoine",
      lastName: "Martin",
      email: "antoine.martin@demo.fr",
      phone: "06 95 60 18 40",
      dob: "1991-12-11",
      maritalStatus: "celibataire",
      taxResidence: "France",
      profession: "Ingenieur software",
      employer: "Aster Labs",
      address: {
        street: "3 place des Jacobins",
        postalCode: "33000",
        city: "Bordeaux",
        country: "France",
      },
      financial: {
        annualIncome: 96000,
        netWorth: 286000,
        realEstateValue: 0,
        financialAssets: 164000,
        liabilities: 24000,
        monthlySavingsCapacity: 2100,
      },
      assets: [
        { id: "asset_am_1", type: "financier", label: "PEA", value: 69000, ownership: 100 },
        { id: "asset_am_2", type: "financier", label: "CTO ETF", value: 54000, ownership: 100 },
        { id: "asset_am_3", type: "autre", label: "Tresorerie", value: 41000, ownership: 100 },
      ],
      riskProfile: "dynamique",
      kycStatus: "complet",
      nextReviewAt: isoDaysOffset(now, 44),
      tags: ["Tech", "ETF"],
      notes: "Client tres autonome, prefere les arbitrages trimestriels digitaux.",
    },
    {
      id: "cl_claire_moreau",
      createdAt: isoDaysOffset(now, -48),
      updatedAt: isoDaysOffset(now, -2),
      firstName: "Claire",
      lastName: "Moreau",
      email: "claire.moreau@demo.fr",
      phone: "06 66 22 49 51",
      dob: "1969-04-20",
      maritalStatus: "divorce",
      taxResidence: "France",
      profession: "Pharmacienne titulaire",
      employer: "Pharmacie des Ternes",
      address: {
        street: "52 rue Bayen",
        postalCode: "75017",
        city: "Paris",
        country: "France",
      },
      financial: {
        annualIncome: 214000,
        netWorth: 2140000,
        realEstateValue: 1180000,
        financialAssets: 690000,
        liabilities: 120000,
        monthlySavingsCapacity: 6200,
      },
      assets: [
        { id: "asset_cm_1", type: "professionnel", label: "Parts officine", value: 620000, ownership: 100 },
        { id: "asset_cm_2", type: "immobilier", label: "Residence principale", value: 760000, ownership: 100 },
        { id: "asset_cm_3", type: "financier", label: "Contrats et tresorerie", value: 690000, ownership: 100 },
      ],
      riskProfile: "prudent",
      kycStatus: "en_cours",
      nextReviewAt: isoDaysOffset(now, 7),
      tags: ["Cession", "Prudent"],
      notes: "Accompagnement de pre-cession et mise en place d'une poche de securisation.",
    },
    {
      id: "cl_julien_rousseau",
      createdAt: isoDaysOffset(now, -35),
      updatedAt: isoDaysOffset(now, -4),
      firstName: "Julien",
      lastName: "Rousseau",
      email: "julien.rousseau@demo.fr",
      phone: "07 44 91 03 27",
      dob: "1985-01-25",
      maritalStatus: "marie",
      taxResidence: "France",
      profession: "Associe cabinet d'avocats",
      employer: "Rousseau Legal",
      address: {
        street: "27 rue de la Republique",
        postalCode: "59800",
        city: "Lille",
        country: "France",
      },
      financial: {
        annualIncome: 236000,
        netWorth: 1260000,
        realEstateValue: 460000,
        financialAssets: 570000,
        liabilities: 140000,
        monthlySavingsCapacity: 7300,
      },
      assets: [
        { id: "asset_jr_1", type: "financier", label: "Contrat capitalisation", value: 320000, ownership: 100 },
        { id: "asset_jr_2", type: "financier", label: "SCPI et private debt", value: 250000, ownership: 100 },
        { id: "asset_jr_3", type: "immobilier", label: "Residence principale", value: 460000, ownership: 100 },
      ],
      riskProfile: "equilibre",
      kycStatus: "complet",
      nextReviewAt: isoDaysOffset(now, 63),
      tags: ["SCPI", "Famille"],
      notes: "Souhaite renforcer les flux de revenus passifs sans alourdir la gestion.",
    },
    {
      id: "cl_emma_fabre",
      createdAt: isoDaysOffset(now, -19),
      updatedAt: isoDaysOffset(now, -1),
      firstName: "Emma",
      lastName: "Fabre",
      email: "emma.fabre@demo.fr",
      phone: "06 87 55 64 98",
      dob: "1994-08-08",
      maritalStatus: "celibataire",
      taxResidence: "France",
      profession: "Product designer",
      employer: "Nexa Digital",
      address: {
        street: "11 rue des Minimes",
        postalCode: "31000",
        city: "Toulouse",
        country: "France",
      },
      financial: {
        annualIncome: 76000,
        netWorth: 168000,
        realEstateValue: 0,
        financialAssets: 89000,
        liabilities: 9000,
        monthlySavingsCapacity: 1600,
      },
      assets: [
        { id: "asset_ef_1", type: "financier", label: "ETF monde", value: 54000, ownership: 100 },
        { id: "asset_ef_2", type: "autre", label: "Tresorerie", value: 35000, ownership: 100 },
      ],
      riskProfile: "equilibre",
      kycStatus: "en_cours",
      nextReviewAt: isoDaysOffset(now, 84),
      tags: ["Digital", "Premier investissement"],
      notes: "Onboarding recent, forte attente sur clarte pedagogique et parcours digital.",
    },
    {
      id: "cl_hugo_chevalier",
      createdAt: isoDaysOffset(now, -9),
      updatedAt: isoDaysOffset(now, 0),
      firstName: "Hugo",
      lastName: "Chevalier",
      email: "hugo.chevalier@demo.fr",
      phone: "07 55 88 12 07",
      dob: "1977-11-17",
      maritalStatus: "marie",
      taxResidence: "Belgique",
      profession: "Entrepreneur",
      employer: "Chevalier Ventures",
      address: {
        street: "221 avenue Louise",
        postalCode: "1050",
        city: "Bruxelles",
        country: "Belgique",
      },
      financial: {
        annualIncome: 348000,
        netWorth: 3980000,
        realEstateValue: 1710000,
        financialAssets: 1540000,
        liabilities: 390000,
        monthlySavingsCapacity: 12400,
      },
      assets: [
        { id: "asset_hc_1", type: "professionnel", label: "Holding patrimoniale", value: 1190000, ownership: 100 },
        { id: "asset_hc_2", type: "immobilier", label: "Immobilier locatif", value: 980000, ownership: 100 },
        { id: "asset_hc_3", type: "financier", label: "Portefeuille multi-banques", value: 1540000, ownership: 100 },
      ],
      riskProfile: "offensif",
      kycStatus: "non_demarre",
      nextReviewAt: isoDaysOffset(now, 18),
      tags: ["Cross-border", "Holding", "UHNW"],
      notes: "Client a fort potentiel, necessite un parcours premium et une coordination transfrontaliere.",
    },
  ];

  const documents: DocumentRecord[] = [
    { id: "doc_1", clientId: "cl_marie_laurent", type: "piece_identite", fileName: "CNI_Marie_Laurent.pdf", status: "verifie", uploadedAt: isoDaysOffset(now, -120), verifiedAt: isoDaysOffset(now, -119), expiresAt: isoDaysOffset(now, 520) },
    { id: "doc_2", clientId: "cl_marie_laurent", type: "justificatif_domicile", fileName: "EDF_Marie_Laurent.pdf", status: "verifie", uploadedAt: isoDaysOffset(now, -117), verifiedAt: isoDaysOffset(now, -116), expiresAt: isoDaysOffset(now, 120) },
    { id: "doc_3", clientId: "cl_marie_laurent", type: "rib", fileName: "RIB_Marie_Laurent.pdf", status: "verifie", uploadedAt: isoDaysOffset(now, -117), verifiedAt: isoDaysOffset(now, -116) },
    { id: "doc_4", clientId: "cl_marie_laurent", type: "source_fonds", fileName: "Origine_Fonds_Marie.pdf", status: "verifie", uploadedAt: isoDaysOffset(now, -113), verifiedAt: isoDaysOffset(now, -112) },

    { id: "doc_5", clientId: "cl_paul_bernard", type: "piece_identite", fileName: "Passeport_Paul_Bernard.pdf", status: "verifie", uploadedAt: isoDaysOffset(now, -86), verifiedAt: isoDaysOffset(now, -85), expiresAt: isoDaysOffset(now, 300) },
    { id: "doc_6", clientId: "cl_paul_bernard", type: "justificatif_domicile", fileName: "Quittance_Paul_Bernard.pdf", status: "en_attente", uploadedAt: isoDaysOffset(now, -5) },
    { id: "doc_7", clientId: "cl_paul_bernard", type: "rib", fileName: "RIB_Paul_Bernard.pdf", status: "verifie", uploadedAt: isoDaysOffset(now, -84), verifiedAt: isoDaysOffset(now, -83) },
    { id: "doc_8", clientId: "cl_paul_bernard", type: "source_fonds", status: "manquant" },

    { id: "doc_9", clientId: "cl_sophie_mercier", type: "piece_identite", fileName: "CNI_Sophie_Mercier.pdf", status: "verifie", uploadedAt: isoDaysOffset(now, -74), verifiedAt: isoDaysOffset(now, -73), expiresAt: isoDaysOffset(now, 1400) },
    { id: "doc_10", clientId: "cl_sophie_mercier", type: "justificatif_domicile", status: "expire", uploadedAt: isoDaysOffset(now, -71), expiresAt: isoDaysOffset(now, -2) },
    { id: "doc_11", clientId: "cl_sophie_mercier", type: "rib", fileName: "RIB_Sophie_Mercier.pdf", status: "verifie", uploadedAt: isoDaysOffset(now, -69), verifiedAt: isoDaysOffset(now, -68) },
    { id: "doc_12", clientId: "cl_sophie_mercier", type: "source_fonds", fileName: "Avis_Imposition_Sophie.pdf", status: "en_attente", uploadedAt: isoDaysOffset(now, -4) },

    { id: "doc_13", clientId: "cl_antoine_martin", type: "piece_identite", fileName: "CNI_Antoine_Martin.pdf", status: "verifie", uploadedAt: isoDaysOffset(now, -60), verifiedAt: isoDaysOffset(now, -59), expiresAt: isoDaysOffset(now, 980) },
    { id: "doc_14", clientId: "cl_antoine_martin", type: "justificatif_domicile", fileName: "Quittance_Antoine_Martin.pdf", status: "verifie", uploadedAt: isoDaysOffset(now, -59), verifiedAt: isoDaysOffset(now, -58), expiresAt: isoDaysOffset(now, 74) },
    { id: "doc_15", clientId: "cl_antoine_martin", type: "rib", fileName: "RIB_Antoine_Martin.pdf", status: "verifie", uploadedAt: isoDaysOffset(now, -58), verifiedAt: isoDaysOffset(now, -57) },
    { id: "doc_16", clientId: "cl_antoine_martin", type: "source_fonds", fileName: "Bulletins_Antoine_Martin.pdf", status: "verifie", uploadedAt: isoDaysOffset(now, -57), verifiedAt: isoDaysOffset(now, -56) },

    { id: "doc_17", clientId: "cl_claire_moreau", type: "piece_identite", fileName: "Passeport_Claire_Moreau.pdf", status: "verifie", uploadedAt: isoDaysOffset(now, -45), verifiedAt: isoDaysOffset(now, -44), expiresAt: isoDaysOffset(now, 780) },
    { id: "doc_18", clientId: "cl_claire_moreau", type: "justificatif_domicile", fileName: "Taxe_Fonciere_Claire.pdf", status: "verifie", uploadedAt: isoDaysOffset(now, -43), verifiedAt: isoDaysOffset(now, -42), expiresAt: isoDaysOffset(now, 48) },
    { id: "doc_19", clientId: "cl_claire_moreau", type: "rib", status: "en_attente", uploadedAt: isoDaysOffset(now, -1) },
    { id: "doc_20", clientId: "cl_claire_moreau", type: "source_fonds", fileName: "Bilan_Claire_Moreau.pdf", status: "verifie", uploadedAt: isoDaysOffset(now, -41), verifiedAt: isoDaysOffset(now, -40) },

    { id: "doc_21", clientId: "cl_julien_rousseau", type: "piece_identite", fileName: "Passeport_Julien_Rousseau.pdf", status: "verifie", uploadedAt: isoDaysOffset(now, -31), verifiedAt: isoDaysOffset(now, -30), expiresAt: isoDaysOffset(now, 1110) },
    { id: "doc_22", clientId: "cl_julien_rousseau", type: "justificatif_domicile", fileName: "Facture_Julien_Rousseau.pdf", status: "verifie", uploadedAt: isoDaysOffset(now, -30), verifiedAt: isoDaysOffset(now, -29), expiresAt: isoDaysOffset(now, 102) },
    { id: "doc_23", clientId: "cl_julien_rousseau", type: "rib", fileName: "RIB_Julien_Rousseau.pdf", status: "verifie", uploadedAt: isoDaysOffset(now, -29), verifiedAt: isoDaysOffset(now, -28) },
    { id: "doc_24", clientId: "cl_julien_rousseau", type: "source_fonds", fileName: "Pieces_Cession_Julien.pdf", status: "verifie", uploadedAt: isoDaysOffset(now, -26), verifiedAt: isoDaysOffset(now, -25) },

    { id: "doc_25", clientId: "cl_emma_fabre", type: "piece_identite", fileName: "CNI_Emma_Fabre.pdf", status: "en_attente", uploadedAt: isoDaysOffset(now, -4) },
    { id: "doc_26", clientId: "cl_emma_fabre", type: "justificatif_domicile", status: "manquant" },
    { id: "doc_27", clientId: "cl_emma_fabre", type: "rib", status: "manquant" },
    { id: "doc_28", clientId: "cl_emma_fabre", type: "source_fonds", status: "manquant" },

    { id: "doc_29", clientId: "cl_hugo_chevalier", type: "piece_identite", status: "manquant" },
    { id: "doc_30", clientId: "cl_hugo_chevalier", type: "justificatif_domicile", status: "manquant" },
  ];

  const compliance: ComplianceDocRecord[] = [
    { id: "cmp_1", clientId: "cl_marie_laurent", type: "compte_rendu", status: "valide", generatedAt: isoDaysOffset(now, -118), validatedAt: isoDaysOffset(now, -117) },
    { id: "cmp_2", clientId: "cl_marie_laurent", type: "lettre_mission", status: "envoye", generatedAt: isoDaysOffset(now, -116), validatedAt: isoDaysOffset(now, -115) },
    { id: "cmp_3", clientId: "cl_marie_laurent", type: "rapport_adequation", status: "valide", generatedAt: isoDaysOffset(now, -7), validatedAt: isoDaysOffset(now, -6) },
    { id: "cmp_4", clientId: "cl_paul_bernard", type: "compte_rendu", status: "valide", generatedAt: isoDaysOffset(now, -83), validatedAt: isoDaysOffset(now, -82) },
    { id: "cmp_5", clientId: "cl_paul_bernard", type: "rapport_adequation", status: "brouillon", generatedAt: isoDaysOffset(now, -3) },
    { id: "cmp_6", clientId: "cl_sophie_mercier", type: "compte_rendu", status: "valide", generatedAt: isoDaysOffset(now, -70), validatedAt: isoDaysOffset(now, -69) },
    { id: "cmp_7", clientId: "cl_sophie_mercier", type: "comparatif_produits", status: "brouillon", generatedAt: isoDaysOffset(now, -2) },
    { id: "cmp_8", clientId: "cl_antoine_martin", type: "compte_rendu", status: "envoye", generatedAt: isoDaysOffset(now, -58), validatedAt: isoDaysOffset(now, -57) },
    { id: "cmp_9", clientId: "cl_claire_moreau", type: "lettre_mission", status: "valide", generatedAt: isoDaysOffset(now, -44), validatedAt: isoDaysOffset(now, -43) },
    { id: "cmp_10", clientId: "cl_claire_moreau", type: "rapport_adequation", status: "brouillon", generatedAt: isoDaysOffset(now, -1) },
    { id: "cmp_11", clientId: "cl_julien_rousseau", type: "comparatif_produits", status: "envoye", generatedAt: isoDaysOffset(now, -24), validatedAt: isoDaysOffset(now, -23) },
    { id: "cmp_12", clientId: "cl_emma_fabre", type: "compte_rendu", status: "brouillon", generatedAt: isoDaysOffset(now, -1) },
  ];

  const submissions: Submission[] = [
    {
      id: "sub_1",
      clientId: "cl_marie_laurent",
      partner: "Cardif",
      product: "Assurance vie premium",
      amount: 240000,
      status: "acces_active",
      openedAt: isoDaysOffset(now, -56),
      updatedAt: isoDaysOffset(now, -5),
      reference: "CAR-2026-0042",
    },
    {
      id: "sub_2",
      clientId: "cl_paul_bernard",
      partner: "Suravenir",
      product: "Contrat retraite multisupport",
      amount: 110000,
      status: "documents_envoyes",
      openedAt: isoDaysOffset(now, -8),
      updatedAt: isoDaysOffset(now, -3),
      reference: "SUR-2026-0113",
    },
    {
      id: "sub_3",
      clientId: "cl_sophie_mercier",
      partner: "Generali",
      product: "Assurance vie architecture ouverte",
      amount: 300000,
      status: "fonds_recus",
      openedAt: isoDaysOffset(now, -16),
      updatedAt: isoDaysOffset(now, -2),
      reference: "GEN-2026-0038",
    },
    {
      id: "sub_4",
      clientId: "cl_claire_moreau",
      partner: "BNP Paribas",
      product: "Contrat de capitalisation",
      amount: 420000,
      status: "preparation",
      openedAt: isoDaysOffset(now, -5),
      updatedAt: isoDaysOffset(now, -1),
      reference: "BNP-2026-0021",
    },
    {
      id: "sub_5",
      clientId: "cl_julien_rousseau",
      partner: "CNP",
      product: "SCPI en assurance vie",
      amount: 180000,
      status: "termine",
      openedAt: isoDaysOffset(now, -21),
      updatedAt: isoDaysOffset(now, -7),
      reference: "CNP-2026-0190",
    },
    {
      id: "sub_6",
      clientId: "cl_hugo_chevalier",
      partner: "Cardif",
      product: "Structuration internationale",
      amount: 850000,
      status: "preparation",
      openedAt: isoDaysOffset(now, -1),
      updatedAt: isoDaysOffset(now, 0),
      reference: "CAR-2026-0102",
    },
  ];

  const alerts: Alert[] = [
    {
      id: "alt_1",
      clientId: "cl_sophie_mercier",
      type: "doc_expire",
      severity: "critical",
      message: "Justificatif de domicile de Sophie Mercier expire et bloque la validation finale.",
      dueAt: isoDaysOffset(now, 2),
      resolved: false,
      createdAt: isoDaysOffset(now, -2),
    },
    {
      id: "alt_2",
      clientId: "cl_paul_bernard",
      type: "doc_manquant",
      severity: "warning",
      message: "Origine des fonds manquante pour Paul Bernard.",
      dueAt: isoDaysOffset(now, 4),
      resolved: false,
      createdAt: isoDaysOffset(now, -3),
    },
    {
      id: "alt_3",
      clientId: "cl_claire_moreau",
      type: "revue_annuelle",
      severity: "warning",
      message: "Revue annuelle de Claire Moreau a planifier cette semaine.",
      dueAt: isoDaysOffset(now, 1),
      resolved: false,
      createdAt: isoDaysOffset(now, -1),
    },
    {
      id: "alt_4",
      clientId: "cl_hugo_chevalier",
      type: "kyc_incomplet",
      severity: "critical",
      message: "Nouveau dossier Hugo Chevalier sans parcours KYC lance.",
      dueAt: isoDaysOffset(now, 1),
      resolved: false,
      createdAt: isoDaysOffset(now, 0),
    },
    {
      id: "alt_5",
      clientId: "cl_emma_fabre",
      type: "suivi_client",
      severity: "info",
      message: "Relance douce recommandee pour finaliser les pieces de Emma Fabre.",
      dueAt: isoDaysOffset(now, 3),
      resolved: false,
      createdAt: isoDaysOffset(now, -1),
    },
    {
      id: "alt_6",
      clientId: "cl_julien_rousseau",
      type: "soumission_bloquee",
      severity: "warning",
      message: "Validation partenaire attendue sur l'etape d'activation des acces CNP.",
      dueAt: isoDaysOffset(now, -2),
      resolved: true,
      createdAt: isoDaysOffset(now, -10),
    },
    {
      id: "alt_7",
      clientId: "cl_marie_laurent",
      type: "revue_annuelle",
      severity: "info",
      message: "Revue patrimoniale de Marie Laurent completee avec succes.",
      resolved: true,
      createdAt: isoDaysOffset(now, -6),
    },
  ];

  const activity: ActivityEvent[] = [
    { id: "act_1", at: isoDaysOffset(now, 0), clientId: "cl_hugo_chevalier", kind: "client_cree", summary: "Nouveau lead premium cree : Hugo Chevalier" },
    { id: "act_2", at: isoDaysOffset(now, -1), clientId: "cl_emma_fabre", kind: "document_recu", summary: "Carte d'identite recue pour Emma Fabre" },
    { id: "act_3", at: isoDaysOffset(now, -1), clientId: "cl_claire_moreau", kind: "doc_genere", summary: "Rapport d'adequation genere pour Claire Moreau" },
    { id: "act_4", at: isoDaysOffset(now, -2), clientId: "cl_sophie_mercier", kind: "soumission_majeure", summary: "Generali : fonds recus pour Sophie Mercier" },
    { id: "act_5", at: isoDaysOffset(now, -3), clientId: "cl_paul_bernard", kind: "kyc_mis_a_jour", summary: "Profil mis a jour : Paul Bernard" },
    { id: "act_6", at: isoDaysOffset(now, -4), clientId: "cl_marie_laurent", kind: "doc_valide", summary: "Rapport d'adequation valide pour Marie Laurent" },
    { id: "act_7", at: isoDaysOffset(now, -5), clientId: "cl_marie_laurent", kind: "soumission_majeure", summary: "Cardif : acces actif pour Marie Laurent" },
    { id: "act_8", at: isoDaysOffset(now, -6), clientId: "cl_antoine_martin", kind: "document_verifie", summary: "Origine des fonds verifiee pour Antoine Martin" },
    { id: "act_9", at: isoDaysOffset(now, -8), clientId: "cl_julien_rousseau", kind: "doc_genere", summary: "Comparatif produits envoye a Julien Rousseau" },
    { id: "act_10", at: isoDaysOffset(now, -11), clientId: "cl_claire_moreau", kind: "soumission_creee", summary: "Soumission BNP Paribas ouverte pour Claire Moreau" },
    { id: "act_11", at: isoDaysOffset(now, -14), clientId: "cl_sophie_mercier", kind: "document_recu", summary: "Justificatifs complementaires recus pour Sophie Mercier" },
    { id: "act_12", at: isoDaysOffset(now, -18), clientId: "cl_emma_fabre", kind: "client_cree", summary: "Client cree : Emma Fabre" },
  ];

  return { clients, documents, compliance, submissions, alerts, activity };
}
